In [4]:
import pandas as pd
g=pd.read_csv('data/students_performance.csv')
display(g.head())
display(g.columns)
print('---')
g.shape[0] # 9.1
g.loc[155,'writing score'] # 9.2
g.describe()
len(g) # 9.1
g.dtypes
#g.info()
print('----')
g.lunch.value_counts()
g['gender'].value_counts()
g['race/ethnicity'].value_counts()
g['lunch'].tolist()
g.index.tolist()
g.loc[400,'race/ethnicity']
g.loc[2,['gender','lunch']]
g.loc[2,['gender']]
g[g['gender'].isin(['female'])]
g[g['math score']==72].count()
g[g['math score']==100].shape[0]
g[g['reading score']==100].shape[0]
g[g['math score']==100].shape[0]
g[(g['math score']==100)|(g['reading score']==100)]
g[(g['math score']==100)&(g['reading score']==100)]
g[(g['math score']==100)&(g['reading score']==100)&(g['writing score']==100)].shape[0]
#g.info()
print('-------')
g['test preparation course'].unique()
#g[g['test preparation course']=='none'].shape[0]
g[g['math score']==0].shape[0] # 9.9

#g[(g['parental level of education']=='high school') & (g['race/ethnicity']=='group C')][g['gender']=='male'][g['test preparation course']=='none'][g['math score'].max()]
#g[g['race/ethnicity']=='group C']
#g[g['lunch']=='standard']['math score'].max()

g[g['math score']==100]['reading score'].mean()
g[g['math score']>98]
g[g['math score']>98][g['reading score']>92]['writing score'].mean()

g[g['lunch']=='standard']['math score'].mean()
g[g['lunch']=='standard']['math score'].max()
g[g['lunch']=='free/reduced']['math score'].mean()   # 9.10

round(g[g['test preparation course']=='completed']['reading score'].mean()) # 9.8

a=g[g['parental level of education']=="bachelor's degree"].shape[0]
#g["parental level of education"].value_counts(normalize=True)
#g["parental level of education"].value_counts()
b=g['math score'].count()
print(round(a/(b/100))) # 9.11

c=g[g['race/ethnicity']=='group A']['writing score'].median()
d=g[g['race/ethnicity']=='group C']['writing score'].mean()
print(round(abs(c-d)))   # 9.12
g.info()
#g.describe(include=['object'])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

---
----
-------
12
6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

C:\Users\Vagabond\AppData\Local\Temp\ipykernel_9108\2262936199.py:41: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  g[g['math score']>98][g['reading score']>92]['writing score'].mean()